apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    app: service
spec:
  containers:
    - name: service-container
      image: gamberfox/lab5-service:latest
      ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: service-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: service
