apiVersion: v1
kind: Pod
metadata:
  name: service-d-pod
  labels:
    app: service-d
spec:
  containers:
    - name: service-d-container
      image: trijuank/service-d:v1    #dockerhub
      ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7000
      protocol: TCP
  selector:
    app: service-d
