apiVersion: v1
kind: Pod
metadata:
  name: service-a-pod
  labels:
    app: service-a
spec:
  containers:
    - name: service-a-container
      image: gamberfox/lab5-service-a:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: service-a
