apiVersion: v1
kind: Pod
metadata:
  name: service-b-pod
  labels:
    app: service-b
spec:
  containers:
    - name: service-b-container
      image: ghcr.io/gustavoa6791/servicio_b_d3_lab5:latest   #github packages
      ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    app: service-b
